score1, score2, score3 = map(int, input("what are your scores: ").split())
#score1 = int(score1)
#scores2 = int(score2)
print(score1, type(score1), score2, type(score2))
#print(score1, type(score1), score2, type(score2))
print(score1  ,score2 ,score3)